import { ROLES } from "../roles";
import { SCENES } from "../scenes";

export const SCENE_4_SCRIPT = {
  id: "SCRIPT_" + SCENES.SCENE_4.id,
  sceneId: SCENES.SCENE_4.id,
  title: SCENES.SCENE_4.title,
  description: SCENES.SCENE_4.description,
  location: SCENES.SCENE_4.location,
  characters: SCENES.SCENE_4.characters,
  props: SCENES.SCENE_4.props,

  dialog: [
    {
      character: ROLES.NARRATOR.id,
      type: "narration",
      text: "Ben, William and John (two colleagues of Ben) arrive at the house.",
      emotion: "suspenseful",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "narration",
      text: "It's dark, and they are trying to keep quiet.",
      emotion: "tense",
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "Alright, the key is under the flowerpot. Jules said it's always there.",
      emotion: "focused",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "William grogi, takut",
      emotion: null,
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "Wait, what if there is a dog? Is there a dog? I'm not great with dogs!",
      emotion: "nervous",
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "Relax, Will. If there is a dog, you can be the distraction. I will do the tech stuff.",
      emotion: "amused",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "Ben tetap mencoba tenang",
      emotion: null,
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "No dogs, just a fake alarm. Let's stay focused. We are here to help Jules avoid a meltdown.",
      emotion: "calm",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "William menemukan kuncinya dan coba buka pintunya",
      emotion: null,
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "aaa… I found it!!!",
      emotion: "excited",
      stage_direction: "setengah teriak",
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "sssttttt … lower your voice will!!",
      emotion: "annoyed",
      stage_direction: "tangan di mulut",
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "The computer should be in the living room. Stick to the plan.",
      emotion: "focused",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "William bisik bisik sambil takut",
      emotion: null,
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "What if Jules's mom walks in? Do we just smile and say, 'Surprise?'",
      emotion: "anxious",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "John sambil memegang senter",
      emotion: null,
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "No, we pretend we're tech support 'Hi ma'am, your internet provider sent us.'",
      emotion: "clever",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "Ben menyeringai",
      emotion: null,
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "Guys, less talking, more moving. Let's go.",
      emotion: "determined",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "Mereka bertiga melihat ada dua laptop di atas meja",
      emotion: null,
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "Which one, Ben? The white or the silver?",
      emotion: "uncertain",
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "The white one. Jules said she recently got it fixed.",
      emotion: "confident",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "William buka laptopnya",
      emotion: null,
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "Got it!!",
      emotion: "excited",
      stage_direction: "setengah teriak",
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "sssttttt … lower your voice will!!",
      emotion: "frustrated",
      stage_direction: "tangan di mulut",
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "Sorry... Subject line... 'Why is my mother always so bothersome...' Wow, I don't even want to read the rest.",
      emotion: "shocked",
      stage_direction: "meringis, angkat tangan sambil kaget",
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "Just delete it and empty the trash. Quickly.",
      emotion: "urgent",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "Tiba - tiba ada bunyi suara alarm",
      emotion: null,
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "What is that?! Are we in a movie?!",
      emotion: "panicked",
      stage_direction: "Setengah teriak",
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "Relax. Jules said it's fake. Just ignore it.",
      emotion: "reassuring",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "William tutup telinga",
      emotion: null,
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "Fake or not, it's too loud enough to wake the whole neighborhood!",
      emotion: "panicked",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "Ben, William dan John buru buru rapiin barang",
      emotion: null,
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "Fantastic. Now we look like actual burglars.",
      emotion: "sarcastic",
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "Great job, Ben. Next time, let's just send an apology bouquet instead.",
      emotion: "exasperated",
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "It's ok, we are clear. Back to the car. Now.",
      emotion: "commanding",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "Buru buru keluar rumah",
      emotion: null,
    },
    {
      character: ROLES.WILLIAM_SQUAT.id,
      type: "dialog",
      text: "I swear, this is the last time I help Jules with one of her 'missions.'",
      emotion: "exasperated",
    },
    {
      character: ROLES.JOHN_DUE.id,
      type: "dialog",
      text: "Yeah, until next week when something else happens.",
      emotion: "amused",
    },
    {
      character: ROLES.BEN_WHITTAKER.id,
      type: "dialog",
      text: "Admit it, you loved the adrenaline. But hey, the email's gone. Mission accomplished.",
      emotion: "satisfied",
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "William sama John tos kegirangan",
      emotion: null,
    },
    {
      character: ROLES.NARRATOR.id,
      type: "stage_direction",
      text: "William dan John mau tos ke Ben tapi bingung, karena Ben biasa jabat tangan",
      emotion: null,
    },
  ],

  stage_directions: {
    initial_setup: "Dark house interior, three men sneaking in",
    lighting: "Dark with flashlights/phone lights",
    mood: "Tense but comedic",
  },

  pronunciation_notes: {
    key_phrases: [
      {
        text: "bothersome",
        ipa: "/ˈbɒðəsəm/",
        emphasis: "Stress on first syllable",
      },
    ],
  },

  emotional_arc: {
    start: "nervous tension",
    middle: "rising panic",
    end: "relief and amusement",
  },
};
